[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite outputs to dist)
  publish = "dist"
  
  # Functions directory (not needed for this project)
  # functions = "netlify/functions"

[build.environment]
  # Node version
  NODE_VERSION = "18"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Development server settings
[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
